### ISSUE TITLE
Echo in coffeescript not supported?

### ISSUE THREAD

**Issue by macr** [jas/gulp-preprocess#11]
I can't get coffeescript to echo any variable. I took a lok at the test to see how it's done but I've found nothing.
```coffeescript
#global define

define [], ->
  "use strict"

  # @exclude NODE_ENV='production'
  superExpensiveFunction()
  # @endexclude

  # @if NODE_ENV='production'
  superExpensiveFunction()
  # @endif

  # @include include.txt
```

The JS fixture on the other hand has it:
```JS
/*global define*/

define([], function () {
  "use strict";

  //@echo firstOption

  //@exclude NODE_ENV='production'
  superExpensiveFunction()
  //@endexclude

  //@if NODE_ENV='production'
  superExpensiveFunction()
  //@endif

  /*@include include.txt */

});
```

**Comment by jas** [comment]
Thanks for opening an issue about this, @macr. Unfortunately this is a problem with the [`preprocess`](https://github.com/jsoverson/preprocess) library rather than `gulp-preprocess`. I suggest opening an issue or pull request for that project, and I'll be happy to update `gulp-preprocess` once a new version of `preprocess` is released.
